version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - 'touch .npmignore'
  pre_build:
    commands:
      - 'yarn install'
  build:
    commands:
      - 'yarn test'
      - 'yarn build'
artifacts:
  base-directory: public
  files:
    - '**/*'
  discard-paths: no
cache:
  paths:
    - '.cache/*'
    - 'public/*'
